name: Upload Python Package

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"      # Stable versions (e.g., 1.0.0)
      - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"  # Alpha versions (e.g., 1.0.0a1)
      - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"  # Beta versions (e.g., 1.0.0b1)
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+" # Release candidates (e.g., 1.0.0rc1)
  release:
    types: [published]

permissions:
  contents: read
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://github.com/SSujitX/pyscreenrecorder
